spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?loggerLevel=OFF}
    username: ${DB_USER:stoom}
    password: ${DB_PASS:stoom}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    default-schema: public
  redis:
    host: ${REDIS_HOST:locahost}
    port: ${REDIS_PORT:6379}
  cache:
    type: REDIS
    redis:
      time-to-live: 600000
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  output:
    ansi:
      enabled: ALWAYS

stoom:
  google:
    api:
      api-key: AIzaSyBm3xh9oZP1ksMWcMzVaZQevWlrtb8tIgc
      base-url: https://maps.googleapis.com/maps/api/geocode/json